export const postContentStyles = {
  '& h1, & h2, & h3': { fontWeight: '600', marginTop: 5, marginBottom: 3 },
  '& p': { marginBottom: 4 },
  '& a': { color: 'fg', textDecoration: 'underline' },
  '& ul, & ol': { paddingLeft: 5, marginBottom: 4 },
  '& table': {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: 4,
    fontSize: 'sm',
  },
  '& th, & td': {
    border: '1px solid',
    borderColor: 'border',
    padding: '8px 10px',
    textAlign: 'left',
  },
  '& th': { bg: 'bg.subtle', fontWeight: '600' },
  '& blockquote': {
    borderLeft: '3px solid',
    borderColor: 'border',
    paddingLeft: 3,
    color: 'fg.muted',
    marginBottom: 4,
  },
  '& .callout': {
    border: '1px solid',
    borderColor: 'border',
    borderRadius: '12px',
    padding: 4,
    marginBottom: 4,
    background: 'bg.subtle',
  },
  '& .callout-note strong': { color: 'fg' },
  '& .callout-tip strong': { color: 'fg' },
  '& .callout-warning strong': { color: 'fg.warning' },
  '& .callout-info strong': { color: 'fg' },
  '& details.spoiler': {
    border: '1px solid',
    borderColor: 'border',
    borderRadius: '12px',
    padding: 3,
    marginBottom: 4,
    background: 'bg.subtle',
  },
  '& details.spoiler summary': {
    cursor: 'pointer',
    fontWeight: '600',
    marginBottom: 2,
  },
  '& .embed': {
    position: 'relative',
    paddingBottom: '56.25%',
    height: 0,
    overflow: 'hidden',
    borderRadius: '12px',
    border: '1px solid',
    borderColor: 'border',
    background: 'bg.subtle',
    marginBottom: 4,
  },
  '& .embed iframe': {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    border: 0,
  },
  '& .md-center': {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 4,
  },
  '& .md-center img': {
    borderRadius: '10px',
    marginTop: 2,
    marginBottom: 2,
  },
  '& img': {
    borderRadius: '10px',
    marginTop: 4,
    marginBottom: 4,
    display: 'block',
    maxWidth: '100%',
    height: 'auto',
  },
  '& code': {
    fontFamily: 'mono',
    fontSize: '0.85em',
    background: 'bg.subtle',
    padding: '2px 6px',
    borderRadius: '6px',
  },
  '& pre': {
    background: 'bg.subtle',
    padding: 4,
    borderRadius: '12px',
    overflowX: 'auto',
    marginBottom: 4,
  },
} as const

export const commentContentStyles = {
  ...postContentStyles,
  '& h1, & h2, & h3': { fontWeight: '600', marginTop: 4, marginBottom: 2 },
  '& p': { marginBottom: 3 },
  '& ul, & ol': { paddingLeft: 5, marginBottom: 3 },
  '& table': {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: 3,
    fontSize: 'sm',
  },
  '& blockquote': {
    borderLeft: '3px solid',
    borderColor: 'border',
    paddingLeft: 3,
    color: 'fg.muted',
    marginBottom: 3,
  },
  '& .callout': {
    border: '1px solid',
    borderColor: 'border',
    borderRadius: '10px',
    padding: 3,
    marginBottom: 3,
    background: 'bg.subtle',
  },
  '& details.spoiler': {
    border: '1px solid',
    borderColor: 'border',
    borderRadius: '10px',
    padding: 2,
    marginBottom: 3,
    background: 'bg.subtle',
  },
  '& .embed': {
    position: 'relative',
    paddingBottom: '56.25%',
    height: 0,
    overflow: 'hidden',
    borderRadius: '10px',
    border: '1px solid',
    borderColor: 'border',
    background: 'bg.subtle',
    marginBottom: 3,
  },
  '& .md-center': {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 3,
  },
  '& img': {
    borderRadius: '8px',
    marginTop: 3,
    marginBottom: 3,
    display: 'block',
    maxWidth: '100%',
    height: 'auto',
  },
  '& pre': {
    background: 'bg.subtle',
    padding: 3,
    borderRadius: '10px',
    overflowX: 'auto',
    marginBottom: 3,
  },
} as const
