export const TAG_PALETTES = [
  'gray',
  'red',
  'orange',
  'yellow',
  'green',
  'teal',
  'blue',
  'cyan',
  'purple',
  'pink',
] as const
export const simpleicon = (slug:string,options?:{color?:string,dark?:string}) => `https://cdn.simpleicons.org/${slug}` + (options?.color ? `/${options.color}` : '') + (options?.dark ? `${!options.color ? '/_' : ''}/${options.dark}` : '')// TODO: add options support
export const flagicon = (countrycode:string) => `https://cdn.jsdelivr.net/gh/lipis/flag-icons@7.5.0/flags/4x3/${countrycode.toLowerCase()}.svg`
export const colorTokens = {
  HIVE: ['#E31337','#fff'],
  HBD:['#00960E','white'],
  INLEO: ['#F4401F','#000'],
  PEAKD:['#333','#FF97AA','#808285']
}
export const HIVE_RED = colorTokens.HIVE[0]
export const INLEO_PRIMARY = colorTokens.INLEO[0]

export type TagPalette = (typeof TAG_PALETTES)[number]

export type TagStyle = {
  bg?: string
  fg?: string
  border?: string
  avatar?: string
  colorPalette?: TagPalette
}
const hiveStyle = { bg: HIVE_RED, fg: colorTokens.HIVE[1], avatar: 'https://cdn.simpleicons.org/hive_blockchain/white' }
const bitcoin =  {
    fg: '#F8931A',
    bg: '#fff',
  }
export const TAG_STYLE_MAP: Record<string, TagStyle> = {
  // Hive ecosystem / projects
  hive: hiveStyle,
  hiveio: hiveStyle,
  hbd: { bg: colorTokens.HBD[0], fg: colorTokens.HBD[1], avatar: simpleicon('hive_blockchain',{color:'white'}) },
  hivepen:{colorPalette:'gray', bg:'#fff', fg:'#722', avatar:'favicon.svg'},
  inleo: { bg: INLEO_PRIMARY, fg: colorTokens.INLEO[1] },
  leofinance: { bg: INLEO_PRIMARY, fg: '#ffffff' },
  leodex: { bg: INLEO_PRIMARY, fg: '#ffffff' },
  leodao: { bg: INLEO_PRIMARY, fg: '#ffffff' },
  ecency: { bg: '#1C8BD9', fg: '#fff' },
  peakd: { bg: colorTokens.PEAKD[0], fg: colorTokens.PEAKD[1] },
  '3speak': { colorPalette: 'purple' },
  dbuzz: { colorPalette: 'blue' },
  dcity: { colorPalette: 'green' },
  splinterlands: { colorPalette: 'purple' },
  risingstar: { colorPalette: 'pink' },
  hiveengine: { colorPalette: 'red' },
  tribaldex: { colorPalette: 'red' },
  hiveblog: { colorPalette: 'gray' },
  hivemind: { colorPalette: 'gray' },
  hivebuzz: { colorPalette: 'yellow' },
  hivesigner: { colorPalette: 'red' },
  hiveauth: { colorPalette: 'red' },
  leothreads: { colorPalette: 'orange' },
  peakmonsters: { colorPalette: 'purple' },
  dhedge: { colorPalette: 'blue' },
  dtube: { colorPalette: 'red' },
  dblog: { colorPalette: 'gray' },
  dmania: { colorPalette: 'cyan' },
  dtravel: { colorPalette: 'green' },
  ditto: { colorPalette: 'blue' },
  dlife: { colorPalette: 'purple' },
  dclick: { colorPalette: 'teal' },
  dapp: { colorPalette: 'blue' },
  hivegaming: { colorPalette: 'purple' },
  hivemusic: { colorPalette: 'pink' },
  hivephotography: { colorPalette: 'cyan' },
  hiveart: { colorPalette: 'orange' },
  hivedev: { colorPalette: 'green' },
  hivesocial: { colorPalette: 'blue' },
  hivescience: { colorPalette: 'teal' },

  //Platforms

  // Software / tools
  vercel: {
    bg: '#000000',
    fg: '#FFFFFF',
    avatar: 'https://svgstack.com/icon/vercel-logo-5188.svg',
  },
  github: {
    bg: '#181717',
    fg: '#FFFFFF',
    avatar: 'https://img.logo.dev/github.com',
  },
  netlify: {
    bg: '#00C7B7',
    fg: '#0E1E25',
    avatar: 'https://img.logo.dev/netlify.com',
  },
  gitlab: {
    bg: '#FC6D26',
    fg: '#FFFFFF',
    avatar: 'https://img.logo.dev/gitlab.com',
  },
  bitbucket: { colorPalette: 'blue' },
  jira: { colorPalette: 'blue' },
  confluence: { colorPalette: 'blue' },
  trello: { colorPalette: 'teal' },
  slack: {
    bg: '#E01E5A',
    fg: '#FFFFFF',
    avatar: 'https://img.logo.dev/slack.com',
  },
  discord: {
    bg: '#5865F2',
    fg: '#FFFFFF',
    avatar: 'https://img.logo.dev/discord.com',
  },
  notion: { bg: '#ffffff', fg: '#111111', border: '#111111' },
  figma: { colorPalette: 'orange' },
  framer: { colorPalette: 'pink' },
  adobe: { colorPalette: 'red' },
  photoshop: { colorPalette: 'blue' },
  illustrator: { colorPalette: 'orange' },
  aftereffects: { colorPalette: 'purple' },
  premiere: { colorPalette: 'purple' },
  blender: { colorPalette: 'orange' },
  unity: { colorPalette: 'gray' },
  unreal: { colorPalette: 'gray' },
  vscode: { colorPalette: 'blue' },
  vim: { colorPalette: 'green' },
  emacs: { colorPalette: 'purple' },
  chrome: { colorPalette: 'yellow' },
  firefox: { colorPalette: 'orange' },
  safari: { colorPalette: 'blue' },
  brave: { colorPalette: 'orange' },
  edge: { colorPalette: 'teal' },
  docker: { colorPalette: 'blue' },
  kubernetes: { colorPalette: 'blue' },
  aws: { colorPalette: 'orange' },
  gcp: { colorPalette: 'red' },
  azure: { colorPalette: 'blue' },
  digitalocean: { colorPalette: 'blue' },
  heroku: { colorPalette: 'purple' },
  supabase: { colorPalette: 'green' },
  firebase: { colorPalette: 'yellow' },
  postgres: { colorPalette: 'blue' },
  mysql: { colorPalette: 'teal' },
  sqlite: { colorPalette: 'gray' },
  mongodb: { colorPalette: 'green' },
  redis: { colorPalette: 'red' },
  graphql: { colorPalette: 'pink' },
  rest: { colorPalette: 'gray' },
  api: { colorPalette: 'gray' },
  react: { bg: '#61DAFB', fg: '#000000' },
  vue: { fg: '#41B883', colorPalette: 'teal', avatar: simpleicon('vuedotjs') },
  svelte: { colorPalette: 'orange' },
  angular: { colorPalette: 'red' },
  nextjs: { colorPalette: 'gray', avatar: simpleicon('nextdotjs') },
  nuxt: { colorPalette: 'green', avatar: simpleicon('nuxt') },
  remix: { colorPalette: 'gray' },
  astro: { colorPalette: 'purple', avatar: simpleicon('astro') },
  solidjs: { colorPalette: 'blue' },
  lit: { colorPalette: 'blue' },
  tailwind: { colorPalette: 'cyan' },
  chakraui: { colorPalette: 'teal' },
  mui: { colorPalette: 'blue' },
  bootstrap: { colorPalette: 'purple' },
  shadcn: { colorPalette: 'gray', avatar: simpleicon('shadcnui') },
  radix: { colorPalette: 'gray' },
  storybook: { colorPalette: 'pink' },
  jest: { colorPalette: 'orange' },
  vitest: { colorPalette: 'yellow' },
  cypress: { colorPalette: 'green' },
  playwright: { colorPalette: 'purple' },
  pnpm: { colorPalette: 'yellow' },
  yarn: { colorPalette: 'blue' },
  npm: { colorPalette: 'red' },
  bun: { colorPalette: 'orange' },
  deno: { colorPalette: 'gray' },
  nodejs: { colorPalette: 'green', avatar: simpleicon('nodedotjs') },
  python: { colorPalette: 'blue' },
  rust: { colorPalette: 'orange' },
  go: { colorPalette: 'cyan' },
  java: { colorPalette: 'red' },
  kotlin: { colorPalette: 'purple' },
  swift: { colorPalette: 'orange' },
  ruby: { colorPalette: 'red' },
  php: { colorPalette: 'blue' },
  csharp: { colorPalette: 'purple' },
  dotnet: { colorPalette: 'purple' },
  typescript: { colorPalette: 'blue' },
  javascript: { bg: '#F7DF1E', fg: '#000000' },
  linux: { colorPalette: 'gray' },
  macos: { colorPalette: 'gray' },
  windows: { colorPalette: 'blue' },

  // Crypto tokens
  btc: bitcoin,
  bitcoin,
  eth: {
    bg: '#497493',
    fg: '#FFFFFF',
  },
  sol: {
    bg: '#9945FF',
    fg: '#FFFFFF',
    avatar: "https://cdn.simpleicons.org/solana"
  },
  solana: {
    bg: '#9945FF',
    fg: '#FFFFFF',
  },
  ada: {
    bg: '#0033AD',
    fg: '#FFFFFF',
  },
  cardano: {
    bg: '#0033AD',
    fg: '#FFFFFF',
  },
  dot: { colorPalette: 'pink' },
  xrp: { colorPalette: 'gray' },
  ltc: { colorPalette: 'gray' },
  bnb: { colorPalette: 'yellow' },
  doge: { colorPalette: 'orange' },
  shib: { colorPalette: 'orange' },
  link: { colorPalette: 'blue' },
  uni: { colorPalette: 'pink' },
  avax: { colorPalette: 'red' },
  matic: { colorPalette: 'purple' },
  op: { colorPalette: 'red' },
  arb: { colorPalette: 'cyan' },
  atom: { colorPalette: 'purple' },
  near: { colorPalette: 'gray' },
  icp: { colorPalette: 'blue' },
  xtz: { colorPalette: 'blue' },
  algo: { colorPalette: 'gray' },
  eos: { colorPalette: 'blue' },
  trx: { colorPalette: 'red' },
  xlm: { colorPalette: 'cyan' },
  fil: { colorPalette: 'blue' },
  hbar: { colorPalette: 'purple' },
  apt: { colorPalette: 'blue' },
  sui: { colorPalette: 'cyan' },
  pepe: { bg: 'green', fg: 'white' },
  aave: { colorPalette: 'purple' },
  crv: { colorPalette: 'blue' },
  snx: { colorPalette: 'purple' },
  gmx: { colorPalette: 'red' },
  inj: { colorPalette: 'purple' },
  rndr: { colorPalette: 'orange' },
  grt: { colorPalette: 'blue' },
  sand: { colorPalette: 'orange' },
  mana: { colorPalette: 'purple' },
  axs: { colorPalette: 'purple' },
  gala: { colorPalette: 'red' },
  enjin: { colorPalette: 'purple' },
  cake: { colorPalette: 'pink' },
  kava: { colorPalette: 'red' },
  ftm: { colorPalette: 'blue' },
  one: { colorPalette: 'blue' },
  zec: { colorPalette: 'gray' },
  dash: { colorPalette: 'blue' },
  monero: { colorPalette: 'orange' },
  xmr: { colorPalette: 'orange' },
  wbtc: { colorPalette: 'yellow' },
  usdt: {
    bg: '#26A17B',
    fg: '#FFFFFF',
    avatar: 'https://crypto-logo.com/128/usdt.svg',
  },
  usdc: {
    bg: '#2775CA',
    fg: '#FFFFFF',
    avatar: 'https://crypto-logo.com/128/usdc.svg',
  },
  dai: { colorPalette: 'yellow' },
  busd: { colorPalette: 'yellow' },
  tusd: { colorPalette: 'blue' },

  // Countries (Americas)
  usa: {
    bg: '#0A3161',
    fg: '#FFFFFF',
    border: '#B31942',
    avatar: flagicon('us'),
  },
  us: {
    bg: '#0A3161',
    fg: '#FFFFFF',
    border: '#B31942',
    avatar: flagicon('us'),
  },
  unitedstates: {
    bg: '#0A3161',
    fg: '#FFFFFF',
    border: '#B31942',
    avatar: flagicon('us'),
  },
  unitedstatesofamerica: {
    bg: '#0A3161',
    fg: '#FFFFFF',
    border: '#B31942',
    avatar: flagicon('us'),
  },
  canada: { colorPalette: 'teal', avatar: flagicon('ca') },
  mexico: { colorPalette: 'teal', avatar: flagicon('mx') },
  brazil: {
    bg: '#009739',
    fg: '#FFFFFF',
    border: '#FEDD00',
    avatar: flagicon('br'),
  },
  argentina: { colorPalette: 'cyan', avatar: flagicon('ar') },
  chile: { colorPalette: 'cyan', avatar: flagicon('cl') },
  colombia: { colorPalette: 'cyan', avatar: flagicon('co') },
  peru: { colorPalette: 'red', avatar: flagicon('pe') },
  venezuela: { colorPalette: 'yellow', avatar: flagicon('ve') },
  ecuador: { colorPalette: 'yellow', avatar: flagicon('ec') },
  bolivia: { colorPalette: 'green', avatar: flagicon('bo') },
  paraguay: { colorPalette: 'red', avatar: flagicon('py') },
  uruguay: { colorPalette: 'cyan', avatar: flagicon('uy') },
  guatemala: { colorPalette: 'blue', avatar: flagicon('gt') },
  honduras: { colorPalette: 'blue', avatar: flagicon('hn') },
  elsalvador: { colorPalette: 'blue', avatar: flagicon('sv') },
  nicaragua: { colorPalette: 'blue', avatar: flagicon('ni') },
  costarica: { colorPalette: 'blue', avatar: flagicon('cr') },
  panama: { colorPalette: 'blue', avatar: flagicon('pa') },
  cuba: { bg: 'white', fg: 'blue', border: 'dodgerblue', avatar: flagicon('cu') },
  dominicanrepublic: { colorPalette: 'blue', avatar: flagicon('do') },
  jamaica: { colorPalette: 'green', avatar: flagicon('jm') },

  // Countries (Europe)
  uk: { colorPalette: 'teal', avatar: flagicon('gb') },
  unitedkingdom: { colorPalette: 'teal', avatar: flagicon('gb') },
  ireland: { colorPalette: 'green', avatar: flagicon('ie') },
  france: {
    bg: '#000091',
    fg: '#FFFFFF',
    border: '#E1000F',
    avatar: flagicon('fr'),
  },
  germany: { colorPalette: 'yellow', avatar: flagicon('de') },
  spain: { colorPalette: 'red', avatar: flagicon('es') },
  italy: { colorPalette: 'green', avatar: flagicon('it') },
  netherlands: { colorPalette: 'orange', avatar: flagicon('nl') },
  belgium: { colorPalette: 'yellow', avatar: flagicon('be') },
  sweden: {
    bg: '#006AA7',
    fg: '#FECC02',
    avatar: flagicon('se'),
  },
  norway: {
    bg: '#00205B',
    fg: '#FFFFFF',
    border: '#BA0C2F',
    avatar: flagicon('no'),
  },
  denmark: { colorPalette: 'red', avatar: flagicon('dk') },
  finland: { colorPalette: 'blue', avatar: flagicon('fi') },
  switzerland: { colorPalette: 'red', avatar: flagicon('ch') },
  austria: { colorPalette: 'red', avatar: flagicon('at') },
  portugal: { colorPalette: 'green', avatar: flagicon('pt') },
  greece: { colorPalette: 'blue', avatar: flagicon('gr') },
  poland: { colorPalette: 'red', avatar: flagicon('pl') },
  czechia: { colorPalette: 'blue', avatar: flagicon('cz') },
  czechrepublic: { colorPalette: 'blue', avatar: flagicon('cz') },
  hungary: { colorPalette: 'green', avatar: flagicon('hu') },
  romania: { colorPalette: 'yellow', avatar: flagicon('ro') },
  bulgaria: { colorPalette: 'green', avatar: flagicon('bg') },
  ukraine: { colorPalette: 'yellow', avatar: flagicon('ua') },
  russia: { colorPalette: 'blue', avatar: flagicon('ru') },
  turkey: { colorPalette: 'red', avatar: flagicon('tr') },

  // Countries (Asia)
  china: { colorPalette: 'red', avatar: flagicon('cn') },
  japan: { colorPalette: 'red', avatar: flagicon('jp') },
  korea: { colorPalette: 'blue', avatar: flagicon('kr') },
  southkorea: { colorPalette: 'blue', avatar: flagicon('kr') },
  northkorea: { colorPalette: 'red', avatar: flagicon('kp') },
  india: {
    bg: '#FF671F',
    fg: '#FFFFFF',
    border: '#046A38',
    avatar: flagicon('in'),
  },
  pakistan: { colorPalette: 'green', avatar: flagicon('pk') },
  bangladesh: { colorPalette: 'green', avatar: flagicon('bd') },
  srilanka: { colorPalette: 'yellow', avatar: flagicon('lk') },
  nepal: { colorPalette: 'red', avatar: flagicon('np') },
  bhutan: { colorPalette: 'orange', avatar: flagicon('bt') },
  indonesia: { colorPalette: 'red', avatar: flagicon('id') },
  malaysia: { colorPalette: 'yellow', avatar: flagicon('my') },
  singapore: { colorPalette: 'red', avatar: flagicon('sg') },
  thailand: { colorPalette: 'red', avatar: flagicon('th') },
  vietnam: { colorPalette: 'red', avatar: flagicon('vn') },
  philippines: { colorPalette: 'blue', avatar: flagicon('ph') },
  cambodia: { colorPalette: 'blue', avatar: flagicon('kh') },
  laos: { colorPalette: 'red', avatar: flagicon('la') },
  myanmar: { colorPalette: 'yellow', avatar: flagicon('mm') },
  taiwan: { colorPalette: 'blue', avatar: flagicon('tw') },
  hongkong: { colorPalette: 'red', avatar: flagicon('hk') },
  uae: { colorPalette: 'green', avatar: flagicon('ae') },
  saudiarabia: { colorPalette: 'green', avatar: flagicon('sa') },
  qatar: { colorPalette: 'purple', avatar: flagicon('qa') },
  kuwait: { colorPalette: 'green', avatar: flagicon('kw') },
  oman: { colorPalette: 'red', avatar: flagicon('om') },
  israel: { colorPalette: 'blue', avatar: flagicon('il') },
  iran: { colorPalette: 'green', avatar: flagicon('ir') },
  iraq: { colorPalette: 'red', avatar: flagicon('iq') },

  // Countries (Africa)
  nigeria: { colorPalette: 'green', avatar: flagicon('ng') },
  southafrica: { colorPalette: 'green', avatar: flagicon('za') },
  kenya: { colorPalette: 'green', avatar: flagicon('ke') },
  uganda: { colorPalette: 'yellow', avatar: flagicon('ug') },
  tanzania: { colorPalette: 'green', avatar: flagicon('tz') },
  ghana: { colorPalette: 'yellow', avatar: flagicon('gh') },
  egypt: { colorPalette: 'yellow', avatar: flagicon('eg') },
  morocco: { colorPalette: 'red', avatar: flagicon('ma') },
  algeria: { colorPalette: 'green', avatar: flagicon('dz') },
  tunisia: { colorPalette: 'red', avatar: flagicon('tn') },
  ethiopia: { colorPalette: 'green', avatar: flagicon('et') },
  sudan: { colorPalette: 'red', avatar: flagicon('sd') },
  angola: { colorPalette: 'red', avatar: flagicon('ao') },

  // Countries (Oceania)
  australia: { colorPalette: 'blue', avatar: flagicon('au') },
  newzealand: { colorPalette: 'blue', avatar: flagicon('nz') },
  fiji: { colorPalette: 'cyan', avatar: flagicon('fj') },
}

export const TAG_REGEX_OVERRIDES: Array<{ pattern: RegExp; style: TagStyle }> = [
  { pattern: /^hive(io)?$/i, style: hiveStyle },
]
