export const TAG_PALETTES = [
  'gray',
  'red',
  'orange',
  'yellow',
  'green',
  'teal',
  'blue',
  'cyan',
  'purple',
  'pink',
] as const

export type TagPalette = (typeof TAG_PALETTES)[number]

export type TagStyle = {
  bg?: string
  fg?: string
  border?: string
  avatar?: string
  colorPalette?: TagPalette
}

export const TAG_STYLE_MAP: Record<string, TagStyle> = {
  // Hive ecosystem / projects
  hive: { colorPalette: 'red' },
  hiveio: { colorPalette: 'red' },
  hbd: { colorPalette: 'yellow' },
  inleo: { bg: '#F4401F', fg: '#000' },
  leofinance: { colorPalette: 'orange' },
  leodex: { colorPalette: 'orange' },
  leodao: { colorPalette: 'orange' },
  ecency: { bg: '#1C8BD9', fg: '#fff' },
  peakd: { colorPalette: 'teal' },
  '3speak': { colorPalette: 'purple' },
  dbuzz: { colorPalette: 'blue' },
  dcity: { colorPalette: 'green' },
  splinterlands: { colorPalette: 'purple' },
  risingstar: { colorPalette: 'pink' },
  hiveengine: { colorPalette: 'red' },
  tribaldex: { colorPalette: 'red' },
  hiveblog: { colorPalette: 'gray' },
  hivemind: { colorPalette: 'gray' },
  hivebuzz: { colorPalette: 'yellow' },
  hivesigner: { colorPalette: 'red' },
  hiveauth: { colorPalette: 'red' },
  leothreads: { colorPalette: 'orange' },
  peakmonsters: { colorPalette: 'purple' },
  dhedge: { colorPalette: 'blue' },
  dtube: { colorPalette: 'red' },
  dblog: { colorPalette: 'gray' },
  dmania: { colorPalette: 'cyan' },
  dtravel: { colorPalette: 'green' },
  ditto: { colorPalette: 'blue' },
  dlife: { colorPalette: 'purple' },
  dclick: { colorPalette: 'teal' },
  dapp: { colorPalette: 'blue' },
  hivegaming: { colorPalette: 'purple' },
  hivemusic: { colorPalette: 'pink' },
  hivephotography: { colorPalette: 'cyan' },
  hiveart: { colorPalette: 'orange' },
  hivedev: { colorPalette: 'green' },
  hivesocial: { colorPalette: 'blue' },
  hivescience: { colorPalette: 'teal' },

  // Software / tools
  vercel: { bg: '#000000', fg: '#ffffff' },
  netlify: { bg: '#00c7b7', fg: '#001b2b' },
  github: { bg: '#0d1117', fg: '#ffffff' },
  gitlab: { bg: '#fc6d26', fg: '#ffffff' },
  bitbucket: { colorPalette: 'blue' },
  jira: { colorPalette: 'blue' },
  confluence: { colorPalette: 'blue' },
  trello: { colorPalette: 'teal' },
  slack: { colorPalette: 'purple' },
  discord: { bg: '#5865f2', fg: '#ffffff' },
  notion: { bg: '#ffffff', fg: '#111111', border: '#111111' },
  figma: { bg: '#0acf83', fg: '#ffffff' },
  framer: { colorPalette: 'pink' },
  adobe: { colorPalette: 'red' },
  photoshop: { colorPalette: 'blue' },
  illustrator: { colorPalette: 'orange' },
  aftereffects: { colorPalette: 'purple' },
  premiere: { colorPalette: 'purple' },
  blender: { colorPalette: 'orange' },
  unity: { colorPalette: 'gray' },
  unreal: { colorPalette: 'gray' },
  vscode: { colorPalette: 'blue' },
  vim: { colorPalette: 'green' },
  emacs: { colorPalette: 'purple' },
  chrome: { colorPalette: 'yellow' },
  firefox: { colorPalette: 'orange' },
  safari: { colorPalette: 'blue' },
  brave: { colorPalette: 'orange' },
  edge: { colorPalette: 'teal' },
  docker: { colorPalette: 'blue' },
  kubernetes: { colorPalette: 'blue' },
  aws: { colorPalette: 'orange' },
  gcp: { colorPalette: 'red' },
  azure: { colorPalette: 'blue' },
  digitalocean: { colorPalette: 'blue' },
  heroku: { colorPalette: 'purple' },
  supabase: { colorPalette: 'green' },
  firebase: { colorPalette: 'yellow' },
  postgres: { colorPalette: 'blue' },
  mysql: { colorPalette: 'teal' },
  sqlite: { colorPalette: 'gray' },
  mongodb: { colorPalette: 'green' },
  redis: { colorPalette: 'red' },
  graphql: { colorPalette: 'pink' },
  rest: { colorPalette: 'gray' },
  api: { colorPalette: 'gray' },
  react: { colorPalette: 'cyan' },
  vue: { colorPalette: 'green' },
  svelte: { colorPalette: 'orange' },
  angular: { colorPalette: 'red' },
  nextjs: { colorPalette: 'gray' },
  nuxt: { colorPalette: 'green' },
  remix: { colorPalette: 'gray' },
  astro: { colorPalette: 'purple' },
  solidjs: { colorPalette: 'blue' },
  lit: { colorPalette: 'blue' },
  tailwind: { colorPalette: 'cyan' },
  chakraui: { colorPalette: 'teal' },
  mui: { colorPalette: 'blue' },
  bootstrap: { colorPalette: 'purple' },
  shadcn: { colorPalette: 'gray' },
  radix: { colorPalette: 'gray' },
  storybook: { colorPalette: 'pink' },
  jest: { colorPalette: 'orange' },
  vitest: { colorPalette: 'yellow' },
  cypress: { colorPalette: 'green' },
  playwright: { colorPalette: 'purple' },
  pnpm: { colorPalette: 'yellow' },
  yarn: { colorPalette: 'blue' },
  npm: { colorPalette: 'red' },
  bun: { colorPalette: 'orange' },
  deno: { colorPalette: 'gray' },
  nodejs: { colorPalette: 'green' },
  python: { colorPalette: 'blue' },
  rust: { colorPalette: 'orange' },
  go: { colorPalette: 'cyan' },
  java: { colorPalette: 'red' },
  kotlin: { colorPalette: 'purple' },
  swift: { colorPalette: 'orange' },
  ruby: { colorPalette: 'red' },
  php: { colorPalette: 'blue' },
  csharp: { colorPalette: 'purple' },
  dotnet: { colorPalette: 'purple' },
  typescript: { colorPalette: 'blue' },
  javascript: { colorPalette: 'yellow' },
  linux: { colorPalette: 'gray' },
  macos: { colorPalette: 'gray' },
  windows: { colorPalette: 'blue' },

  // Crypto tokens
  btc: { bg: '#FFB119', fg: '#000' },
  eth: { colorPalette: 'purple' },
  sol: { colorPalette: 'cyan' },
  ada: { colorPalette: 'blue' },
  dot: { colorPalette: 'pink' },
  xrp: { colorPalette: 'gray' },
  ltc: { colorPalette: 'gray' },
  bnb: { colorPalette: 'yellow' },
  doge: { colorPalette: 'orange' },
  shib: { colorPalette: 'orange' },
  link: { colorPalette: 'blue' },
  uni: { colorPalette: 'pink' },
  avax: { colorPalette: 'red' },
  matic: { colorPalette: 'purple' },
  op: { colorPalette: 'red' },
  arb: { colorPalette: 'cyan' },
  atom: { colorPalette: 'purple' },
  near: { colorPalette: 'gray' },
  icp: { colorPalette: 'blue' },
  xtz: { colorPalette: 'blue' },
  algo: { colorPalette: 'gray' },
  eos: { colorPalette: 'blue' },
  trx: { colorPalette: 'red' },
  xlm: { colorPalette: 'cyan' },
  fil: { colorPalette: 'blue' },
  hbar: { colorPalette: 'purple' },
  apt: { colorPalette: 'blue' },
  sui: { colorPalette: 'cyan' },
  pepe: { colorPalette: 'green' },
  aave: { colorPalette: 'purple' },
  crv: { colorPalette: 'blue' },
  snx: { colorPalette: 'purple' },
  gmx: { colorPalette: 'red' },
  inj: { colorPalette: 'purple' },
  rndr: { colorPalette: 'orange' },
  grt: { colorPalette: 'blue' },
  sand: { colorPalette: 'orange' },
  mana: { colorPalette: 'purple' },
  axs: { colorPalette: 'purple' },
  gala: { colorPalette: 'red' },
  enjin: { colorPalette: 'purple' },
  cake: { colorPalette: 'pink' },
  kava: { colorPalette: 'red' },
  ftm: { colorPalette: 'blue' },
  one: { colorPalette: 'blue' },
  zec: { colorPalette: 'gray' },
  dash: { colorPalette: 'blue' },
  monero: { colorPalette: 'orange' },
  xmr: { colorPalette: 'orange' },
  wbtc: { colorPalette: 'yellow' },
  usdt: { colorPalette: 'green' },
  usdc: { colorPalette: 'blue' },
  dai: { colorPalette: 'yellow' },
  busd: { colorPalette: 'yellow' },
  tusd: { colorPalette: 'blue' },

  // Countries (Americas)
  usa: { colorPalette: 'blue' },
  us: { colorPalette: 'blue' },
  unitedstates: { colorPalette: 'blue' },
  unitedstatesofamerica: { colorPalette: 'blue' },
  canada: { colorPalette: 'teal' },
  mexico: { colorPalette: 'teal' },
  brazil: {
    bg: '#009440',
    fg: '#FFCB02',
    border: '#ffffff',
    avatar:
      'https://upload.wikimedia.org/wikipedia/en/thumb/0/05/Flag_of_Brazil.svg/250px-Flag_of_Brazil.svg.png',
  },
  argentina: { colorPalette: 'cyan' },
  chile: { colorPalette: 'cyan' },
  colombia: { colorPalette: 'cyan' },
  peru: { colorPalette: 'red' },
  venezuela: { colorPalette: 'yellow' },
  ecuador: { colorPalette: 'yellow' },
  bolivia: { colorPalette: 'green' },
  paraguay: { colorPalette: 'red' },
  uruguay: { colorPalette: 'cyan' },
  guatemala: { colorPalette: 'blue' },
  honduras: { colorPalette: 'blue' },
  elsalvador: { colorPalette: 'blue' },
  nicaragua: { colorPalette: 'blue' },
  costarica: { colorPalette: 'blue' },
  panama: { colorPalette: 'blue' },
  cuba: { colorPalette: 'red' },
  dominicanrepublic: { colorPalette: 'blue' },
  jamaica: { colorPalette: 'green' },

  // Countries (Europe)
  uk: { colorPalette: 'teal' },
  unitedkingdom: { colorPalette: 'teal' },
  ireland: { colorPalette: 'green' },
  france: { colorPalette: 'blue' },
  germany: { colorPalette: 'yellow' },
  spain: { colorPalette: 'red' },
  italy: { colorPalette: 'green' },
  netherlands: { colorPalette: 'orange' },
  belgium: { colorPalette: 'yellow' },
  sweden: { colorPalette: 'yellow' },
  norway: { colorPalette: 'red' },
  denmark: { colorPalette: 'red' },
  finland: { colorPalette: 'blue' },
  switzerland: { colorPalette: 'red' },
  austria: { colorPalette: 'red' },
  portugal: { colorPalette: 'green' },
  greece: { colorPalette: 'blue' },
  poland: { colorPalette: 'red' },
  czechia: { colorPalette: 'blue' },
  czechrepublic: { colorPalette: 'blue' },
  hungary: { colorPalette: 'green' },
  romania: { colorPalette: 'yellow' },
  bulgaria: { colorPalette: 'green' },
  ukraine: { colorPalette: 'yellow' },
  russia: { colorPalette: 'blue' },
  turkey: { colorPalette: 'red' },

  // Countries (Asia)
  china: { colorPalette: 'red' },
  japan: { colorPalette: 'red' },
  korea: { colorPalette: 'blue' },
  southkorea: { colorPalette: 'blue' },
  northkorea: { colorPalette: 'red' },
  india: { colorPalette: 'orange' },
  pakistan: { colorPalette: 'green' },
  bangladesh: { colorPalette: 'green' },
  srilanka: { colorPalette: 'yellow' },
  nepal: { colorPalette: 'red' },
  bhutan: { colorPalette: 'orange' },
  indonesia: { colorPalette: 'red' },
  malaysia: { colorPalette: 'yellow' },
  singapore: { colorPalette: 'red' },
  thailand: { colorPalette: 'red' },
  vietnam: { colorPalette: 'red' },
  philippines: { colorPalette: 'blue' },
  cambodia: { colorPalette: 'blue' },
  laos: { colorPalette: 'red' },
  myanmar: { colorPalette: 'yellow' },
  taiwan: { colorPalette: 'blue' },
  hongkong: { colorPalette: 'red' },
  uae: { colorPalette: 'green' },
  saudiarabia: { colorPalette: 'green' },
  qatar: { colorPalette: 'purple' },
  kuwait: { colorPalette: 'green' },
  oman: { colorPalette: 'red' },
  israel: { colorPalette: 'blue' },
  iran: { colorPalette: 'green' },
  iraq: { colorPalette: 'red' },

  // Countries (Africa)
  nigeria: { colorPalette: 'green' },
  southafrica: { colorPalette: 'green' },
  kenya: { colorPalette: 'green' },
  uganda: { colorPalette: 'yellow' },
  tanzania: { colorPalette: 'green' },
  ghana: { colorPalette: 'yellow' },
  egypt: { colorPalette: 'yellow' },
  morocco: { colorPalette: 'red' },
  algeria: { colorPalette: 'green' },
  tunisia: { colorPalette: 'red' },
  ethiopia: { colorPalette: 'green' },
  sudan: { colorPalette: 'red' },
  angola: { colorPalette: 'red' },

  // Countries (Oceania)
  australia: { colorPalette: 'blue' },
  newzealand: { colorPalette: 'blue' },
  fiji: { colorPalette: 'cyan' },
}

export const TAG_REGEX_OVERRIDES: Array<{ pattern: RegExp; style: TagStyle }> = [
  { pattern: /^hive(io)?$/i, style: { colorPalette: 'red' } },
]
