/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunitiesIndexRouteImport } from './routes/communities.index'
import { Route as AccountnameIndexRouteImport } from './routes/$accountname.index'
import { Route as ProfileAccountnameRouteImport } from './routes/profile.$accountname'
import { Route as CommunitiesCommunityIdRouteImport } from './routes/communities.$communityId'
import { Route as AccountnameWalletRouteImport } from './routes/$accountname.wallet'
import { Route as AccountnameWalletIndexRouteImport } from './routes/$accountname.wallet.index'
import { Route as PostAuthorPermlinkRouteImport } from './routes/post.$author.$permlink'
import { Route as AccountnameWalletHpRouteImport } from './routes/$accountname.wallet.hp'
import { Route as AccountnameWalletHiveRouteImport } from './routes/$accountname.wallet.hive'
import { Route as AccountnameWalletHbdRouteImport } from './routes/$accountname.wallet.hbd'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesIndexRoute = CommunitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunitiesRoute,
} as any)
const AccountnameIndexRoute = AccountnameIndexRouteImport.update({
  id: '/$accountname/',
  path: '/$accountname/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAccountnameRoute = ProfileAccountnameRouteImport.update({
  id: '/profile/$accountname',
  path: '/profile/$accountname',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunityIdRoute = CommunitiesCommunityIdRouteImport.update({
  id: '/$communityId',
  path: '/$communityId',
  getParentRoute: () => CommunitiesRoute,
} as any)
const AccountnameWalletRoute = AccountnameWalletRouteImport.update({
  id: '/$accountname/wallet',
  path: '/$accountname/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountnameWalletIndexRoute = AccountnameWalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountnameWalletRoute,
} as any)
const PostAuthorPermlinkRoute = PostAuthorPermlinkRouteImport.update({
  id: '/post/$author/$permlink',
  path: '/post/$author/$permlink',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountnameWalletHpRoute = AccountnameWalletHpRouteImport.update({
  id: '/hp',
  path: '/hp',
  getParentRoute: () => AccountnameWalletRoute,
} as any)
const AccountnameWalletHiveRoute = AccountnameWalletHiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => AccountnameWalletRoute,
} as any)
const AccountnameWalletHbdRoute = AccountnameWalletHbdRouteImport.update({
  id: '/hbd',
  path: '/hbd',
  getParentRoute: () => AccountnameWalletRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/editor': typeof EditorRoute
  '/engagement': typeof EngagementRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/$accountname/wallet': typeof AccountnameWalletRouteWithChildren
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/profile/$accountname': typeof ProfileAccountnameRoute
  '/$accountname/': typeof AccountnameIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/$accountname/wallet/hbd': typeof AccountnameWalletHbdRoute
  '/$accountname/wallet/hive': typeof AccountnameWalletHiveRoute
  '/$accountname/wallet/hp': typeof AccountnameWalletHpRoute
  '/post/$author/$permlink': typeof PostAuthorPermlinkRoute
  '/$accountname/wallet/': typeof AccountnameWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/editor': typeof EditorRoute
  '/engagement': typeof EngagementRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/profile/$accountname': typeof ProfileAccountnameRoute
  '/$accountname': typeof AccountnameIndexRoute
  '/communities': typeof CommunitiesIndexRoute
  '/$accountname/wallet/hbd': typeof AccountnameWalletHbdRoute
  '/$accountname/wallet/hive': typeof AccountnameWalletHiveRoute
  '/$accountname/wallet/hp': typeof AccountnameWalletHpRoute
  '/post/$author/$permlink': typeof PostAuthorPermlinkRoute
  '/$accountname/wallet': typeof AccountnameWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/editor': typeof EditorRoute
  '/engagement': typeof EngagementRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/$accountname/wallet': typeof AccountnameWalletRouteWithChildren
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/profile/$accountname': typeof ProfileAccountnameRoute
  '/$accountname/': typeof AccountnameIndexRoute
  '/communities/': typeof CommunitiesIndexRoute
  '/$accountname/wallet/hbd': typeof AccountnameWalletHbdRoute
  '/$accountname/wallet/hive': typeof AccountnameWalletHiveRoute
  '/$accountname/wallet/hp': typeof AccountnameWalletHpRoute
  '/post/$author/$permlink': typeof PostAuthorPermlinkRoute
  '/$accountname/wallet/': typeof AccountnameWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/communities'
    | '/dashboard'
    | '/drafts'
    | '/editor'
    | '/engagement'
    | '/search'
    | '/settings'
    | '/users'
    | '/$accountname/wallet'
    | '/communities/$communityId'
    | '/profile/$accountname'
    | '/$accountname/'
    | '/communities/'
    | '/$accountname/wallet/hbd'
    | '/$accountname/wallet/hive'
    | '/$accountname/wallet/hp'
    | '/post/$author/$permlink'
    | '/$accountname/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/dashboard'
    | '/drafts'
    | '/editor'
    | '/engagement'
    | '/search'
    | '/settings'
    | '/users'
    | '/communities/$communityId'
    | '/profile/$accountname'
    | '/$accountname'
    | '/communities'
    | '/$accountname/wallet/hbd'
    | '/$accountname/wallet/hive'
    | '/$accountname/wallet/hp'
    | '/post/$author/$permlink'
    | '/$accountname/wallet'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/communities'
    | '/dashboard'
    | '/drafts'
    | '/editor'
    | '/engagement'
    | '/search'
    | '/settings'
    | '/users'
    | '/$accountname/wallet'
    | '/communities/$communityId'
    | '/profile/$accountname'
    | '/$accountname/'
    | '/communities/'
    | '/$accountname/wallet/hbd'
    | '/$accountname/wallet/hive'
    | '/$accountname/wallet/hp'
    | '/post/$author/$permlink'
    | '/$accountname/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DraftsRoute: typeof DraftsRoute
  EditorRoute: typeof EditorRoute
  EngagementRoute: typeof EngagementRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  AccountnameWalletRoute: typeof AccountnameWalletRouteWithChildren
  ProfileAccountnameRoute: typeof ProfileAccountnameRoute
  AccountnameIndexRoute: typeof AccountnameIndexRoute
  PostAuthorPermlinkRoute: typeof PostAuthorPermlinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/': {
      id: '/communities/'
      path: '/'
      fullPath: '/communities/'
      preLoaderRoute: typeof CommunitiesIndexRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/$accountname/': {
      id: '/$accountname/'
      path: '/$accountname'
      fullPath: '/$accountname/'
      preLoaderRoute: typeof AccountnameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$accountname': {
      id: '/profile/$accountname'
      path: '/profile/$accountname'
      fullPath: '/profile/$accountname'
      preLoaderRoute: typeof ProfileAccountnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communityId': {
      id: '/communities/$communityId'
      path: '/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof CommunitiesCommunityIdRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/$accountname/wallet': {
      id: '/$accountname/wallet'
      path: '/$accountname/wallet'
      fullPath: '/$accountname/wallet'
      preLoaderRoute: typeof AccountnameWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$accountname/wallet/': {
      id: '/$accountname/wallet/'
      path: '/'
      fullPath: '/$accountname/wallet/'
      preLoaderRoute: typeof AccountnameWalletIndexRouteImport
      parentRoute: typeof AccountnameWalletRoute
    }
    '/post/$author/$permlink': {
      id: '/post/$author/$permlink'
      path: '/post/$author/$permlink'
      fullPath: '/post/$author/$permlink'
      preLoaderRoute: typeof PostAuthorPermlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$accountname/wallet/hp': {
      id: '/$accountname/wallet/hp'
      path: '/hp'
      fullPath: '/$accountname/wallet/hp'
      preLoaderRoute: typeof AccountnameWalletHpRouteImport
      parentRoute: typeof AccountnameWalletRoute
    }
    '/$accountname/wallet/hive': {
      id: '/$accountname/wallet/hive'
      path: '/hive'
      fullPath: '/$accountname/wallet/hive'
      preLoaderRoute: typeof AccountnameWalletHiveRouteImport
      parentRoute: typeof AccountnameWalletRoute
    }
    '/$accountname/wallet/hbd': {
      id: '/$accountname/wallet/hbd'
      path: '/hbd'
      fullPath: '/$accountname/wallet/hbd'
      preLoaderRoute: typeof AccountnameWalletHbdRouteImport
      parentRoute: typeof AccountnameWalletRoute
    }
  }
}

interface CommunitiesRouteChildren {
  CommunitiesCommunityIdRoute: typeof CommunitiesCommunityIdRoute
  CommunitiesIndexRoute: typeof CommunitiesIndexRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesCommunityIdRoute: CommunitiesCommunityIdRoute,
  CommunitiesIndexRoute: CommunitiesIndexRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

interface AccountnameWalletRouteChildren {
  AccountnameWalletHbdRoute: typeof AccountnameWalletHbdRoute
  AccountnameWalletHiveRoute: typeof AccountnameWalletHiveRoute
  AccountnameWalletHpRoute: typeof AccountnameWalletHpRoute
  AccountnameWalletIndexRoute: typeof AccountnameWalletIndexRoute
}

const AccountnameWalletRouteChildren: AccountnameWalletRouteChildren = {
  AccountnameWalletHbdRoute: AccountnameWalletHbdRoute,
  AccountnameWalletHiveRoute: AccountnameWalletHiveRoute,
  AccountnameWalletHpRoute: AccountnameWalletHpRoute,
  AccountnameWalletIndexRoute: AccountnameWalletIndexRoute,
}

const AccountnameWalletRouteWithChildren =
  AccountnameWalletRoute._addFileChildren(AccountnameWalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DraftsRoute: DraftsRoute,
  EditorRoute: EditorRoute,
  EngagementRoute: EngagementRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  AccountnameWalletRoute: AccountnameWalletRouteWithChildren,
  ProfileAccountnameRoute: ProfileAccountnameRoute,
  AccountnameIndexRoute: AccountnameIndexRoute,
  PostAuthorPermlinkRoute: PostAuthorPermlinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
