/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrototypeRouteImport } from './routes/prototype'
import { Route as EngagementRouteImport } from './routes/engagement'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileAccountnameRouteImport } from './routes/profile.$accountname'
import { Route as CommunitiesCommunityIdRouteImport } from './routes/communities.$communityId'
import { Route as PostAuthorPermlinkRouteImport } from './routes/post.$author.$permlink'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeRoute = PrototypeRouteImport.update({
  id: '/prototype',
  path: '/prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementRoute = EngagementRouteImport.update({
  id: '/engagement',
  path: '/engagement',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAccountnameRoute = ProfileAccountnameRouteImport.update({
  id: '/profile/$accountname',
  path: '/profile/$accountname',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesCommunityIdRoute = CommunitiesCommunityIdRouteImport.update({
  id: '/$communityId',
  path: '/$communityId',
  getParentRoute: () => CommunitiesRoute,
} as any)
const PostAuthorPermlinkRoute = PostAuthorPermlinkRouteImport.update({
  id: '/post/$author/$permlink',
  path: '/post/$author/$permlink',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/blog': typeof BlogRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/editor': typeof EditorRoute
  '/engagement': typeof EngagementRoute
  '/prototype': typeof PrototypeRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/profile/$accountname': typeof ProfileAccountnameRoute
  '/post/$author/$permlink': typeof PostAuthorPermlinkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/blog': typeof BlogRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/editor': typeof EditorRoute
  '/engagement': typeof EngagementRoute
  '/prototype': typeof PrototypeRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/profile/$accountname': typeof ProfileAccountnameRoute
  '/post/$author/$permlink': typeof PostAuthorPermlinkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/blog': typeof BlogRoute
  '/communities': typeof CommunitiesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/editor': typeof EditorRoute
  '/engagement': typeof EngagementRoute
  '/prototype': typeof PrototypeRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
  '/communities/$communityId': typeof CommunitiesCommunityIdRoute
  '/profile/$accountname': typeof ProfileAccountnameRoute
  '/post/$author/$permlink': typeof PostAuthorPermlinkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/blog'
    | '/communities'
    | '/dashboard'
    | '/drafts'
    | '/editor'
    | '/engagement'
    | '/prototype'
    | '/search'
    | '/settings'
    | '/users'
    | '/communities/$communityId'
    | '/profile/$accountname'
    | '/post/$author/$permlink'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/blog'
    | '/communities'
    | '/dashboard'
    | '/drafts'
    | '/editor'
    | '/engagement'
    | '/prototype'
    | '/search'
    | '/settings'
    | '/users'
    | '/communities/$communityId'
    | '/profile/$accountname'
    | '/post/$author/$permlink'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/blog'
    | '/communities'
    | '/dashboard'
    | '/drafts'
    | '/editor'
    | '/engagement'
    | '/prototype'
    | '/search'
    | '/settings'
    | '/users'
    | '/communities/$communityId'
    | '/profile/$accountname'
    | '/post/$author/$permlink'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BlogRoute: typeof BlogRoute
  CommunitiesRoute: typeof CommunitiesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DraftsRoute: typeof DraftsRoute
  EditorRoute: typeof EditorRoute
  EngagementRoute: typeof EngagementRoute
  PrototypeRoute: typeof PrototypeRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
  ProfileAccountnameRoute: typeof ProfileAccountnameRoute
  PostAuthorPermlinkRoute: typeof PostAuthorPermlinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype': {
      id: '/prototype'
      path: '/prototype'
      fullPath: '/prototype'
      preLoaderRoute: typeof PrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement': {
      id: '/engagement'
      path: '/engagement'
      fullPath: '/engagement'
      preLoaderRoute: typeof EngagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$accountname': {
      id: '/profile/$accountname'
      path: '/profile/$accountname'
      fullPath: '/profile/$accountname'
      preLoaderRoute: typeof ProfileAccountnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$communityId': {
      id: '/communities/$communityId'
      path: '/$communityId'
      fullPath: '/communities/$communityId'
      preLoaderRoute: typeof CommunitiesCommunityIdRouteImport
      parentRoute: typeof CommunitiesRoute
    }
    '/post/$author/$permlink': {
      id: '/post/$author/$permlink'
      path: '/post/$author/$permlink'
      fullPath: '/post/$author/$permlink'
      preLoaderRoute: typeof PostAuthorPermlinkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CommunitiesRouteChildren {
  CommunitiesCommunityIdRoute: typeof CommunitiesCommunityIdRoute
}

const CommunitiesRouteChildren: CommunitiesRouteChildren = {
  CommunitiesCommunityIdRoute: CommunitiesCommunityIdRoute,
}

const CommunitiesRouteWithChildren = CommunitiesRoute._addFileChildren(
  CommunitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BlogRoute: BlogRoute,
  CommunitiesRoute: CommunitiesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DraftsRoute: DraftsRoute,
  EditorRoute: EditorRoute,
  EngagementRoute: EngagementRoute,
  PrototypeRoute: PrototypeRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
  ProfileAccountnameRoute: ProfileAccountnameRoute,
  PostAuthorPermlinkRoute: PostAuthorPermlinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
